#!/usr/bin/env bash
# This Bash script configures Nginx server so that /redirect_me is redirecting to another page

sudo apt -y update
sudo apt -y install nginx

echo "Hello World!" > /var/www/html/index.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart
