#!/usr/bin/env bash
# This Bash script configures your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt -y update
sudo apt -y install nginx

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i 's/server_name _;/server_name _;\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;\n\terror_page 404 \/404.html;\n\tlocation \/404.html{\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/' /etc/nginx/sites-enabled/default

sudo service nginx restart
