#!/usr/bin/env bash
# This Bash script configure Nginx so that its HTTP response contains a custom header (on 258926-web-01 and 258926-web-02) 

sudo apt-get update
sudo apt-get -y install nginx
sudo chown $USER:$USER /var/www/html/index.html
sudo touch index.html /var/www/html/
echo 'Hello world!' > /var/www/html/index.html
sudo mkdir /var/www/error
sudo chown  $USER:$USER /var/www/error/
echo "Ceci n'est pas une page" > /var/www/error/404.html
sudo chown  $USER:$USER /etc/nginx/sites-available/
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.github.com/omotomiwa26 permanent; }' /etc/nginx/sites-available/default
sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/error/; internal; }' /etc/nginx/sites-available/default
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
