#!/usr/bin/env bash
# This Bash script Install and configure HAproxy on 258926-lb-01 server.

sudo apt-get update
sudo apt-get upgrade -y
sudo apt install haproxy -y

server_config="
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 258926-web-01 52.3.243.47:80 check
    server 258926-web-02 100.25.165.37:80 check
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy start
