#!/usr/bin/env bash
# This bash script stops the "4-to_infinity_and_beyond" process
# without using kill or killall

pid="$$(pgrep 4-to_infinity_and_beyond)"

if [ -n "$pid" ]; then
  
  pkill -15 -P "$pid"
  echo "Process $pid (4-to_infinity_and_beyond) has been sent a SIGTERM signal to stop."
else
  echo "Process 4-to_infinity_and_beyond is not running."
fi