#!/usr/bin/env bash
# This script prints and displays "Best School" 10 times using While Loop but prints "Best School" and "Hi" for the 9th iteration

count=0

while [ $count -lt 10 ]
do
    if [ $count -eq 8 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    count=$((count + 1))
done