#!/usr/bin/env bash
# This Bash Script accepts one argument and run the whoami command under the user passed as an argument

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

username=$1 

su -c "whoami" "$username"
