#!/usr/bin/env bash
# This Bash Script fixes container nginx & listening on all active IPs on port 8080
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
su nginx -s /bin/bash -c 'service nginx restart'
