#!/usr/bin/env bash

# This bash script uses ssh to connect to your server using the private # key ~/.ssh/school with the user ubuntu.

ssh -i ~/.ssh/school ubuntu@52.3.243.47

# ssh -i server_1_prv_key ubuntu@52.3.243.47

