#!/usr/bin/env bash

# This bash script uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.

ssh -i ~/.ssh/school -o "PasswordAuthentication no" ubuntu@52.3.243.47

